### ISSUE TITLE
Infinite recursion in baseURL 

### ISSUE THREAD

**Issue by kulakowka** [softonic/axios-retry#16]
I received a very strange bug:

![2017-07-05 9 45 47](https://user-images.githubusercontent.com/557190/27852172-c0066118-6166-11e7-9e7a-ea218cd65139.png)

My configuration looks like this:

![2017-07-05 10 07 51](https://user-images.githubusercontent.com/557190/27852973-d77df470-6169-11e7-957f-e6972fff9395.png)

If you specify the full base url ("http://localhost:3000/api/"), then everything works:

![2017-07-05 10 06 31](https://user-images.githubusercontent.com/557190/27852919-a7ba64d0-6169-11e7-9bcc-e8facf9d54b3.png)

**Comment by rubennorte** [comment]
I just inspected Axios code and the cause of that bug is that Axios resolves the full URL before calling interceptors, so we receive the built URL in `config.url` and `config.baseURL` still has a value. We could fix that in our side but I think that's something Axios should handle (internally removing baseURL once it's used or resolving URL's just before the request must be made).

Would you consider creating a PR there?

**Comment by kulakowka** [comment]
I'm afraid that I can not even formulate the problem correctly. ^_^

**Comment by rubennorte** [comment]
This is already fixed in https://github.com/mzabriskie/axios/pull/950 so it'll work fine in axios-retry when it's released.

**Comment by JulesAU** [comment]
I'm running the latest Axios (0.17.1) and I'm still seeing this behaviour.  Have had to specify an absolute baseURL to work around it.
